language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo install --version 0.9.3 cargo-tarpaulin
  fi

script:
  - cargo clean
  - cargo build
  - cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUST_BACKTRACE=full cargo tarpaulin --out Xml --run-types Tests --run-types Doctests
    bash <(curl -s https://codecov.io/bash)
  fi