[package]
name = "hyeong"
version = "0.1.1-dev"
authors = ["buttercrab <jaeyong0201@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/buttercrab/hyeo-ung-lang"
repository = "https://github.com/buttercrab/hyeo-ung-lang"
description = "Hyeo-ung Programming Language Compiler"

[badges]
travis-ci = { repository = "buttercrab/hyeo-ung-lang" }

[dependencies]
clap = "2.33.0"
colored = "1.9"
ctrlc = { version = "3.0", features = ["termination"] }

[[bin]]
path = "src/main.rs"
name = "hyeong"