[package]
name = "hyeong"
version = "0.1.0-beta.2"
authors = ["buttercrab <jaeyong0201@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
colored = "1.9"
ctrlc = { version = "3.0", features = ["termination"] }
