name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ stable, beta, nightly, macos ]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
          - build: nightly
            os: ubuntu-latest
            rust: nightly
          - build: macos
            os: macos-latest
            rust: stable

    steps:
      - uses: actions/checkout@master

      - name: Setting up rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy

      - name: Cargo Clippy
        run: cargo clippy -- -D warnings

      - name: Build and run tests
        run: cargo test

  fmt:
    name: fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Checking if code is formatted
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check